### ISSUE TITLE
Sections

### ISSUE THREAD

**Issue by ebacachu** [cyschneck/centerline-width#1]
In the same way that we can export the rivercenterline, could we export the sections?

**Comment by cyschneck** [comment]
What are you referring to when you say sections? Subsections of the river?

**Comment by ebacachu** [comment]
Intersecting lines
![Ag5TUTCizx](https://github.com/cyschneck/centerline-width/assets/76530879/8dc26626-4d1f-4514-bd35-9380942d3d77)

**Comment by cyschneck** [comment]
The green line that is circled here is the width line (measuring the width from the right to the left bank)

To return the position of the width line you can use the [`riverWidthFromCenterline` function](https://github.com/cyschneck/centerline-width#return-width-of-river). This return the width line as a `(Longitude, Latitude) : width` where the position `(Longitude, Latitude)` is the position along the centerline (in blue above)

Is that the section information you need?

**Comment by ebacachu** [comment]
I have seen that riverWidthFromCenterline function. returns  (Longitude, Latitude) and width. But with that I can't get the coordinates of the lines, I would need at least two coordinates of each line to define them.
That is, the intersection points of width lines and bank lines could be obtained? This is how each of the width lines would be defined

**Comment by cyschneck** [comment]
You'd like to get the coordinates of where the width line intersects on the left/right bank?

I don't believe I currently have a function in place to get this information (although it is being used on the backend). I will see about adding it today and bundle it with a release

**Comment by ebacachu** [comment]
I would like to be able to obtain its coordinates from each of the width lines, that is, where it begins and where it ends. Thank you

**Comment by cyschneck** [comment]
[New release!](https://github.com/cyschneck/centerline-width/releases/tag/v1.3.0) 

v1.3.0 has the update for `riverWidthFromCenterline()` with the new option  `coordinate_reference="Banks"`. Update also works when the output is saved via `save_to_csv` with new column headers

_Example:_
```
river_width_dict = river.riverWidthFromCenterline(transect_span_distance=transect,
						apply_smoothing=True,
						remove_intersections=True,
						coordinate_reference="Banks",
						save_to_csv=None)
```

**Comment by ebacachu** [comment]
Wonderfull, thanks
